modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="create_silver"
version="1.0.0"
displayName="Create: Netherless Redux"
displayURL=""
credits=""
description="My personal take on Create: Netherless, ported to NeoForge 1.21.1!"
authors="OrcaABXY"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.create_silver]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_silver]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.create_silver]]
    modId="create"
    type="required"
    versionRange="[6.0.6,)"
    ordering="NONE"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration